{
 "title": "Multi-Tenant Platform Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_cpu_usage_seconds_total, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate (Ingress)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{kubernetes_name=\"ingress-nginx-controller\"}[2m])",
     "legendFormat": "HTTP {{code}} scrapes/s"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_consumergroup_lag > 0", "legendFormat": "{{consumergroup}} - {{topic}}" },
    {
     "expr": "kafka_topic_partition_current_offset",
     "legendFormat": "Offset: {{topic}}[{{partition}}]"
    }
   ]
  }
 ]
}